# Generated by Django 5.2.8 on 2025-11-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Patient Name")),
                (
                    "p_id",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Patient ID (e.g., P-101)",
                    ),
                ),
                ("age", models.IntegerField()),
                ("admission_date", models.DateField(auto_now_add=True)),
                (
                    "disease",
                    models.CharField(default="Under Observation", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Stable", "Stable"),
                            ("Critical", "Critical"),
                            ("ICU", "ICU"),
                            ("Discharged", "Discharged"),
                        ],
                        default="Stable",
                        max_length=20,
                    ),
                ),
                (
                    "next_test",
                    models.CharField(
                        default="No tests scheduled",
                        help_text="Example: MRI at 4 PM",
                        max_length=200,
                    ),
                ),
                (
                    "doctor_note",
                    models.TextField(
                        default="Patient is responding to treatment.",
                        help_text="Message for relatives in simple language",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes"),
                ),
            ],
        ),
    ]
