# Generated by Django 5.2.8 on 2025-11-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="doctor_reviewed",
            field=models.CharField(default=False),
        ),
    ]
