# Generated by Django 5.2.8 on 2025-11-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_patient_doctor_reviewed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="doctor_reviewed",
            new_name="reviewer_doctor_name",
        ),
        migrations.AddField(
            model_name="patient",
            name="plan_of_action",
            field=models.TextField(
                default="Continue current treatment and monitor vitals.",
                help_text="Doctor's detailed plan of action",
            ),
        ),
    ]
