# Generated by Django 5.2.8 on 2025-11-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_doctor_reviewed_patient_reviewer_doctor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="next_visit_panned",
            field=models.TextField(
                default="Next visit scheduled as per treatment plan.",
                help_text="Details of next visit planned for the patient",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="prcedure_planned",
            field=models.TextField(
                default="No procedures planned.",
                help_text="Planned procedures for the patient",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="treatment_given",
            field=models.TextField(
                default="Standard treatment as per diagnosis.",
                help_text="Details of treatment given to the patient",
            ),
        ),
    ]
