# Generated by Django 5.2.8 on 2025-11-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_patient_next_visit_panned_patient_prcedure_planned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="diagnosis",
            field=models.CharField(default="Not Specified", max_length=255),
        ),
    ]
