# Generated by Django 5.2.8 on 2025-11-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_patient_diagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
